version: "3.7"

services:
  server:
    image: node:12-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGHOST: db
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - dollar-plan-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}

volumes:
  dollar-plan-db-data:
